
export const HOMEPAGE_ROUTE="/"
export const REGISTER_ROUTE="/register"
export const LOGIN_ROUTE="/login"
export const USER_PAGE_ROUTE="/user/:id"
export const ACCOUNT_ROUTE="/account/:id"
export const CATALOGUE_PAGE_ROUTE="/catalogue"
export const CATALOGUE_PAGE_ITEM_ROUTE="/catalogue/:id"
export const ADD_ROUTE="/add"
export const TOVAR_INFO_PAGE_ROUTE="/tovarInfo/:id"
export const PRODUCTS_PAGE_ROUTE="/products"